import type { NextPage, NextPageContext } from "next";
import { getSession, signOut, useSession } from "next-auth/react";
import Head from "next/head";

const Home: NextPage = () => {
  const { data: session } = useSession();
  return (
    <>
      {!session && (
        <div className="items-center space-y-4 justify-center flex flex-col">
          <Head>
            <title>Next JS Blog</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
        </div>
      )}
    </>
  );
};

export default Home;
export async function getServerSideProps(context: NextPageContext) {
  const session = await getSession(context);
  if (session) {
    context.res?.writeHead(302, { Location: "/" });
    context.res?.end();
    return {};
  }
  return {
    props: { session },
  };
}
